### ISSUE TITLE
Consolidate two mongodb queries into one

### ISSUE THREAD

**Issue by fantasydigit** [fantasydigit/EA-MT4-Demo#2]
I have two mongoDB queries one is aggregate and another one is a find. They are coded in a way that if "aggregate" query gives result then "find" query doesn't run, otherwise, if "aggregate" gives no result then find query runs. In the following way.
In simple words for a request, we check if the requester is in a group if yes, then we return config rule based on this group, If the requester is not in any group then we return general config rule.

So my query is as seen above these are two different query running on different collection, and requires two separate mongo calls. Can I somehow combine these queries into 1 query?, Like- If for a given user he is in a group return group-specific config or return general config rule.

I want to combine these so that in my code I will need to make only one DB call(this db call itself has both query consolidated in one) instead of two.

**Comment by MarcosOpolis** [comment]
please set configType at line 23 and set user_id at line 31
